version: '3.8'
services:
  app:
    container_name: node_api
    build: .
    depends_on:
      - postgres
      - mysql
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      # - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
      - postgres-data:/var/lib/postgresql/data
  
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password --skip-mysqlx
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE_POST: mysql_db2
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  postgres-data:
  mysql-data:
  app-data:
